apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: rabbitmq-source-sink
  namespace: concurrent-dispatch
spec:
  template:
    spec:
      containers:
        - image: gcr.io/knative-releases/knative.dev/eventing/cmd/event_display
