apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  name: default
  namespace: trigger-customizations-sample
  annotations:
    eventing.knative.dev/broker.class: RabbitMQBroker
spec:
  config:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: RabbitmqBrokerConfig
    name: default-config
