# RabbitMQ cluster used by the Broker
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
  namespace: rabbitmq-mtls-sample
spec:
  replicas: 1
  tls:
    secretName: server-secret
    caSecretName: ca-secret
  rabbitmq:
    additionalConfig: |
      ssl_options.fail_if_no_peer_cert = true
  override:
    statefulSet:
      spec:
        template:
          spec:
            containers:
            - name: rabbitmq
              env:
              - name: ERL_MAX_PORTS
                value: "4096"
