run:
  timeout: 5m

  build-tags:
    - e2e

  skip-dirs:
    - pkg/client
    - pkg/internal/thirdparty
    - pkg/dispatcher

linters:
  enable:
    - unconvert
    - prealloc
  disable:
    - errcheck
