apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret-credentials
  namespace: source-sample
# This is just a sample, don't use it this way in production
stringData:
  username: $EXTERNAL_RABBITMQ_USERNAME
  password: $EXTERNAL_RABBITMQ_PASSWORD
  uri: $EXTERNAL_RABBITMQ_MANAGEMENT_UI_URI:$PORT
