apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: default
  namespace: tracing-sample
spec:
  broker: default
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: subscriber
      namespace: tracing-sample

