apiVersion: sources.eventing.knative.dev/v1alpha1
kind: RabbitmqSource
metadata:
  name: rabbitmq-source
  namespace: rabbitsource
spec:
  vhost: RABBITMQ_CLUSTER_VHOST
  rabbitmqClusterReference:
    name: RABBITMQ_CLUSTERREF_NAME
    namespace: RABBITMQ_CLUSTERREF_NAMESPACE
  retry: 5
  backoffPolicy: "linear"
  backoffDelay: "50ms"
  predeclared: false
  exchangeConfig:
    name: RABBITMQ_EXCHANGE_CONFIG_NAME
  queueConfig:
    name: RABBITMQ_QUEUE_CONFIG_NAME
  sink:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: event-display
    namespace: rabbitsource
