apiVersion: sources.eventing.knative.dev/v1alpha1
kind: RabbitmqSource
metadata:
  name: rabbitmq-source
  namespace: rabbitsource
spec:
  broker: RABBITMQ_BROKER
  retry: 5
  backoffPolicy: "linear"
  backoffDelay: "50ms"
  predeclared: false
  user:
    secretKeyRef:
      name: RABBITMQ_USER
      key: RABBITMQ_USER
  password:
    secretKeyRef:
      name: RABBITMQ_PASSWORD
      key: RABBITMQ_PASSWORD
  connectionSecret:
    name: RABBITMQ_CONNECTION_SECRET
  exchangeConfig:
    name: RABBITMQ_EXCHANGE_CONFIG_NAME
  queueConfig:
    name: RABBITMQ_QUEUE_CONFIG_NAME
  sink:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: event-display
    namespace: rabbitsource
