apiVersion: sources.knative.dev/v1alpha1
kind: RabbitmqSource
metadata:
  name: rabbitmq-source
  namespace: external-cluster-sample
spec:
  rabbitmqClusterReference:
    connectionSecret:
      name: rabbitmq-secret-credentials # a secret with your external cluster credentials
  rabbitmqResourcesConfig:
    predeclared: true # For this to be false, the Topology Operator must be installed in the Source's cluster
    # https://www.rabbitmq.com/kubernetes/operator/using-topology-operator.html
    # Value must be between 1 and 1000
    # A value of 1 RabbitMQ Source behaves as a FIFO queue
    # Values above 1 break message ordering guarantees and can be seen as more performance oriented
    # parallelism: 10
    # vhost: you-rabbitmq-vhost
    exchangeName: "eventing-rabbitmq-source"
    queueName: "eventing-rabbitmq-source"
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: event-display
      namespace: external-cluster-sample
