apiVersion: sources.knative.dev/v1alpha1
kind: RabbitmqSource
metadata:
  name: rabbitmq-source
  namespace: concurrent-dispatch
spec:
  brokers: "rabbitmq:5672/"
  topic: ""
  user:
    secretKeyRef:
      name: rabbitmq-default-user
      key: username
  password:
    secretKeyRef:
      name: rabbitmq-default-user
      key: password
  channel_config:
    # prefetch_count default value is 1
    # A value of 0 will default to 1
    # Value must be between 1 and 1000
    # prefetch_count: 10 // default value is 1 FIFO
    global_qos: false
  exchange_config:
    name: "eventing-rabbitmq-source"
    type: "fanout"
    durable: false
    auto_deleted: false
    internal: false
    nowait: false
  queue_config:
    name: "eventing-rabbitmq-source"
    routing_key: ""
    durable: false
    # TODO: Why is the queue not deleted 30 minutes after the source is deleted?
    # https://github.com/knative-sandbox/eventing-rabbitmq/issues/528
    delete_when_unused: true
    # TODO: SHORT-TERM FIX
    # Ensures that the queue is deleted when the Source is deleted
    exclusive: true
    nowait: false
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: rabbitmq-source-sink
      namespace: concurrent-dispatch
