apiVersion: eventing.knative.dev/v1alpha1
kind: RabbitmqBrokerConfig
metadata:
  name: default-config
  namespace: external-cluster-sample
spec:
  # vhost: you-rabbitmq-vhost
  rabbitmqClusterReference:
    namespace: external-cluster-sample
    connectionSecret:
      name: rabbitmq-secret-credentials # a secret with your external cluster credentials
  queueType: quorum
