apiVersion: eventing.knative.dev/v1alpha1
kind: RabbitmqBrokerConfig
metadata:
  name: default-config
  namespace: rabbitmq-mtls-sample
spec:
  # vhost: test-vhost
  rabbitmqClusterReference:
    namespace: rabbitmq-mtls-sample
    name: rabbitmq
  queueType: quorum
