apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  name: default
  namespace: rabbitmq-mtls-sample
  annotations:
    eventing.knative.dev/broker.class: RabbitMQBroker
spec:
  config:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: RabbitmqBrokerConfig
    name: default-config
  delivery:
    deadLetterSink:
      ref:
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: event-display
        namespace: rabbitmq-mtls-sample
    retry: 5
